<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{

    public function findByMedia($id) {

        $qb = $this->createQueryBuilder('c');
        $qb->where('c.media_id = :id');
        $qb->setParameter('id', $id);
 
        return $qb->getQuery()->getResult();
    }

	public function getOwnerId($id) {
		$query = "SELECT user_id FROM comment WHERE id = ?";
		$params = array($id);

		$sth = $this->getEntityManager()->getConnection()->prepare($query);
		$sth->execute($params);
		$row = $sth->fetch();

		return $row['user_id'];
	}

	public function hasVote($user_id, $comment_id) {
		$query = "SELECT COUNT(*) AS CNT FROM comment_votes WHERE user_id = ? AND comment_id = ?";
		$params = array($user_id, $comment_id);

		$sth = $this->getEntityManager()->getConnection()->prepare($query);
		$sth->execute($params);
		$row = $sth->fetch();

		return $row['CNT'] >= 1;
	}

	public function addVote($user_id, $comment_id) {
		$query = "INSERT INTO comment_votes (user_id, comment_id) VALUES (?, ?)";
		$params = array($user_id, $comment_id);

		$sth = $this->getEntityManager()->getConnection()->prepare($query);
		$sth->execute($params);
	}

	public function listVoted($comment_id) {
		$query = "SELECT u.id, u.name FROM comment_votes v INNER JOIN user u ON u.id = v.user_id WHERE v.comment_id = ?";
		$params = array($comment_id);

		$sth = $this->getEntityManager()->getConnection()->prepare($query);
		$sth->execute($params);
		return $sth->fetchAll();
	}

	public function numVotes($comment_id) {
		$query = "SELECT COUNT(*) AS CNT FROM comment_votes WHERE comment_id = ?";
		$params = array($comment_id);

		$sth = $this->getEntityManager()->getConnection()->prepare($query);
		$sth->execute($params);
		$row = $sth->fetch();

		return $row['CNT'];
	}
}
