<?php

namespace AppBundle\Repository;

/**
 * IndustryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustryRepository extends \Doctrine\ORM\EntityRepository
{
	public function findByIndustry($industry)
    {
        return $this->getEntityManager()->createQuery("SELECT i FROM AppBundle:Industry i WHERE i.name LIKE :industry")->setParameter('industry', '%'.$industry.'%')->getResult();
    }

    public function getIndustryList() {
		$query = "SELECT * FROM industry ORDER BY name";

		$sth = $this->getEntityManager()->getConnection()->prepare($query);
		$sth->execute();

		$records = array();

		foreach($sth->fetchAll() as $record) {
			$records[$record['name']] = $record['id'];
		}

		return $records;
    }
}
